const adverbsData = {
  adverbs: {
    title: "Polish Adverbs",
    description:
      "Explore a comprehensive collection of Polish adverbs. Learn how to form adverbs from adjectives, and discover different categories such as time, frequency, manner, place, degree, question, connecting, and negation adverbs. Each section includes examples and English translations to help you understand their usage in context.",
    modalDescription:
      "Comprehensive list of Polish adverbs, organized by category, including meanings and example usage. Includes rules on how to form adverbs from adjectives.",
    sections: [
      {
        id: "formation",
        title: "How to Form Polish Adverbs",
        modalDescription:
          "In Polish, many adverbs come from adjectives. Most follow a regular pattern, while others are irregular. Below are the main rules.",
        modalTitle: "Forming Adverbs from Adjectives",
        modalDescription:
          "Rules and patterns for forming adverbs from adjectives, including irregular forms.",
        columns: [
          "Rule",
          "modalDescription",
          "Example",
          "English",
          "Pattern / Notes",
        ],
        rows: [
          [
            "Adverbs from Adjectives (-o ending)",
            "Most adverbs are formed from the neuter singular form of adjectives by changing the ending to -o.",
            "ładny → ładnie",
            "pretty → nicely",
            "adjective (neuter form) → replace -e with -o",
          ],
          [
            "Adverbs ending in -nie or -cie",
            "Some adjectives create adverbs ending in -nie or -cie. Often abstract or mental-state adjectives.",
            "dokładny → dokładnie",
            "precise → precisely",
            "",
          ],
          [
            "Irregular Adverbs",
            "A small group of adverbs does not follow the standard adjective → adverb transformation.",
            "dobry → dobrze",
            "good → well",
            "",
          ],
          [
            "Adverbs Not Formed from Adjectives",
            "Many adverbs are independent words and do not come from adjectives. Must be memorized.",
            "teraz",
            "now",
            "",
          ],
        ],
      },
      {
        id: "time",
        title: "Adverbs of Time",
        modalDescription: "Indicate when something happens.",
        modalTitle: "Adverbs of Time",
        columns: ["Adverb", "English", "Example"],
        rows: [
          ["teraz", "now", "Teraz idę do domu. – I am going home now."],
          ["wczoraj", "yesterday", "Wczoraj pracowałem. – I worked yesterday."],
          [
            "dziś / dzisiaj",
            "today",
            "Dzisiaj mam lekcję. – Today I have a lesson.",
          ],
          ["jutro", "tomorrow", "Jutro wyjeżdżam. – I leave tomorrow."],
          ["zaraz", "in a moment", "Zaraz wracam. – I’ll be right back."],
          ["później", "later", "Porozmawiamy później. – We will talk later."],
          ["wcześnie", "early", "Wstałem wcześnie. – I got up early."],
          ["późno", "late", "Przyszedłem późno. – I arrived late."],
          [
            "niedawno",
            "recently",
            "Niedawno się poznaliśmy. – We met recently.",
          ],
        ],
      },
      {
        id: "frequency",
        title: "Adverbs of Frequency",
        modalDescription: "Describe how often something happens.",
        modalTitle: "Adverbs of Frequency",
        columns: ["Adverb", "English", "Example"],
        rows: [
          [
            "zawsze",
            "always",
            "Zawsze piję kawę rano. – I always drink coffee in the morning.",
          ],
          ["często", "often", "Często biegam. – I often run."],
          [
            "zwykle",
            "usually",
            "Zwykle pracuję z domu. – I usually work from home.",
          ],
          ["czasami", "sometimes", "Czasami gotuję. – Sometimes I cook."],
          ["rzadko", "rarely", "Rzadko oglądam TV. – I rarely watch TV."],
          ["nigdy", "never", "Nigdy nie jem mięsa. – I never eat meat."],
        ],
      },
      {
        id: "manner",
        title: "Adverbs of Manner",
        modalDescription: "Explain how an action is done.",
        modalTitle: "Adverbs of Manner",
        columns: ["Adverb", "English", "Example"],
        rows: [
          ["szybko", "quickly", "Biegnę szybko. – I run quickly."],
          ["wolno / powoli", "slowly", "Mów wolno. – Speak slowly."],
          ["dokładnie", "precisely", "Czytaj dokładnie. – Read carefully."],
          ["łatwo", "easily", "Zadanie było łatwo. – The task was easy."],
          ["ciężko", "hard / heavily", "Pracuję ciężko. – I work hard."],
          ["głośno", "loudly", "Mów głośno. – Speak loudly."],
          ["cicho", "quietly", "On mówi cicho. – He speaks quietly."],
          ["źle", "badly", "Źle śpię. – I sleep badly."],
          ["dobrze", "well", "Mówię dobrze po polsku. – I speak Polish well."],
        ],
      },
      {
        id: "place",
        title: "Adverbs of Place",
        modalDescription: "Describe location or direction.",
        modalTitle: "Adverbs of Place",
        columns: ["Adverb", "English", "Example"],
        rows: [
          ["tutaj / tu", "here", "Mieszkam tutaj. – I live here."],
          ["tam", "there", "Idę tam. – I am going there."],
          ["wszędzie", "everywhere", "Szukam wszędzie. – I search everywhere."],
          [
            "nigdzie",
            "nowhere",
            "Nigdzie nie mogę znaleźć. – I can’t find it anywhere.",
          ],
          [
            "blisko",
            "near",
            "Mieszkam blisko szkoły. – I live near the school.",
          ],
          ["daleko", "far", "To jest daleko. – It is far."],
          ["w górę", "up", "Idź w górę. – Go up."],
          ["w dół", "down", "Idź w dół. – Go down."],
          ["naprzód", "forward", "Idź naprzód. – Go forward."],
        ],
      },
      {
        id: "degree",
        title: "Adverbs of Degree",
        modalDescription: "Indicate intensity or amount.",
        modalTitle: "Adverbs of Degree",
        columns: ["Adverb", "English", "Example"],
        rows: [
          ["bardzo", "very", "Jest bardzo ładnie. – It is very nice."],
          [
            "trochę",
            "a little",
            "Mówię trochę po polsku. – I speak a little Polish.",
          ],
          [
            "dość / dosyć",
            "quite / rather",
            "To jest dość trudne. – It is quite difficult.",
          ],
          ["prawie", "almost", "Prawie skończyłem. – I almost finished."],
          ["zbyt", "too (much)", "Zbyt dużo pracy. – Too much work."],
          ["w pełni", "fully", "W pełni rozumiem. – I fully understand."],
        ],
      },
      {
        id: "question",
        title: "Question Adverbs",
        modalDescription: "Used to form questions.",
        modalTitle: "Question Adverbs",
        columns: ["Adverb", "English", "Example"],
        rows: [
          ["kiedy?", "when?", "Kiedy jedziesz? – When are you going?"],
          ["gdzie?", "where?", "Gdzie mieszkasz? – Where do you live?"],
          ["dokąd?", "to where?", "Dokąd idziesz? – Where are you going to?"],
          ["skąd?", "from where?", "Skąd jesteś? – Where are you from?"],
          ["jak?", "how?", "Jak się masz? – How are you?"],
          ["dlaczego?", "why?", "Dlaczego płacisz? – Why are you paying?"],
          [
            "po co?",
            "for what purpose?",
            "Po co to robisz? – Why are you doing this?",
          ],
        ],
      },
      {
        id: "connecting",
        title: "Connecting / Linking Adverbs",
        modalDescription: "Useful for storytelling and writing.",
        modalTitle: "Connecting Adverbs",
        columns: ["Adverb", "English", "Example"],
        rows: [
          [
            "więc",
            "so",
            "Jest zimno, więc zostaję w domu. – It is cold, so I stay home.",
          ],
          ["potem", "then", "Potem poszedłem spać. – Then I went to sleep."],
          ["następnie", "next", "Następnie czytaliśmy. – Next we read."],
          [
            "w końcu",
            "finally",
            "W końcu zrozumiałem. – I finally understood.",
          ],
          ["jednak", "however", "Jednak nie mogę. – However, I can’t."],
        ],
      },
      {
        id: "negation",
        title: "Negation Adverbs",
        modalDescription: "Used to negate verbs and statements.",
        modalTitle: "Negation",
        columns: ["Adverb", "English", "Example"],
        rows: [["nie", "not", "Nie rozumiem. – I do not understand."]],
      },
    ],
  },
};

export default adverbsData;
