const numbersData = {
  // --- CARDINAL NUMBERS ---
  cardinal_0_10: {
    title: "0–10",
    description: "Basic numbers / Podstawowe liczby",
    modalTitle: "Polish Cardinal Numbers 0-10",
    columns: ["Number", "Polish Word"],
    rows: [
      ["0", "zero"],
      ["1", "jeden"],
      ["2", "dwa"],
      ["3", "trzy"],
      ["4", "cztery"],
      ["5", "pięć"],
      ["6", "sześć"],
      ["7", "siedem"],
      ["8", "osiem"],
      ["9", "dziewięć"],
      ["10", "dziesięć"],
    ],
  },
  cardinal_10_100: {
    title: "10–100",
    description: "Key tens / Kluczowe dziesiątki",
    modalTitle: "Polish Cardinal Numbers 10-100",
    columns: ["Number", "Polish Word", "Note"],
    rows: [
      ["10", "dziesięć", ""],
      ["11", "jedenaście", "Ends in -naście"],
      ["15", "piętnaście", "Ends in -naście"],
      ["20", "dwadzieścia", "Ends in -dzieścia"],
      ["30", "trzydzieści", "Ends in -dzieści"],
      ["40", "czterdzieści", "Ends in -dzieści"],
      ["50", "pięćdziesiąt", "Ends in -dziesiąt"],
      ["99", "dziewięćdziesiąt dziewięć", "Example of a compound number"],
      ["100", "sto", ""],
    ],
  },
  cardinal_100_1000: {
    title: "100–1000",
    description: "Hundreds / Setki",
    modalTitle: "Polish Cardinal Hundreds",
    columns: ["Number", "Polish Word"],
    rows: [
      ["100", "sto"],
      ["200", "dwieście"],
      ["300", "trzysta"],
      ["400", "czterysta"],
      ["500", "pięćset"],
      ["999", "dziewięćset dziewięćdziesiąt dziewięć"],
      ["1000", "tysiąc"],
    ],
  },
  cardinal_1000_plus: {
    title: "1000–1,000,000",
    description: "Thousands & millions / Tysiące i miliony",
    modalTitle: "Polish Cardinal Thousands & Millions",
    columns: ["Number", "Polish Word", "Note"],
    rows: [
      ["1000", "tysiąc", "Masculine noun, requires proper case"],
      ["2000", "dwa tysiące", "Tysiące for 2, 3, 4"],
      ["5000", "pięć tysięcy", "Tysięcy for 5+"],
      ["1,000,000", "milion", "Masculine noun"],
    ],
  },

  // --- ORDINAL NUMBERS ---
  ordinal_1_10: {
    title: "1–10",
    description: "Basic ordinals / Podstawowe liczby porządkowe",
    modalTitle: "Polish Ordinal Numbers 1-10",
    columns: ["Ordinal", "Polish Word (Masc.)", "Note"],
    rows: [
      ["1st", "pierwszy", "Like an adjective, declines by case/gender"],
      ["2nd", "drugi", ""],
      ["3rd", "trzeci", ""],
      ["4th", "czwarty", ""],
      ["5th", "piąty", ""],
      ["6th", "szósty", ""],
      ["7th", "siódmy", ""],
      ["8th", "ósmy", ""],
      ["9th", "dziewiąty", ""],
      ["10th", "dziesiąty", ""],
    ],
  },
  ordinal_10_100: {
    title: "10–100",
    description: "Key tens ordinals / Kluczowe dziesiątki porządkowe",
    modalTitle: "Polish Ordinal Key Tens",
    columns: ["Ordinal", "Polish Word (Masc.)"],
    rows: [
      ["20th", "dwudziesty"],
      ["30th", "trzydziesty"],
      ["40th", "czterdziesty"],
      ["50th", "pięćdziesiąty"],
      ["99th", "dziewięćdziesiąty dziewiąty"],
      ["100th", "setny"],
    ],
  },
  ordinal_100_1000: {
    title: "100–1000",
    description: "Hundreds ordinals / Setki porządkowe",
    modalTitle: "Polish Ordinal Hundreds",
    columns: ["Ordinal", "Polish Word (Masc.)"],
    rows: [
      ["100th", "setny"],
      ["200th", "dwusetny"],
      ["300th", "trzystetny"],
      ["400th", "czterysetny"],
      ["500th", "pięćsetny"],
    ],
  },
  ordinal_1000_plus: {
    title: "1000–1,000,000",
    description: "Thousands & millions ordinals / Tysiące i miliony porządkowe",
    modalTitle: "Polish Ordinal Thousands & Millions",
    columns: ["Ordinal", "Polish Word (Masc.)"],
    rows: [
      ["1,000th", "tysięczny"],
      ["1,000,000th", "milionowy"],
    ],
  },
};

export default numbersData;
