const possessivePronounsData = {
  pronouns: {
    title: "Polish Possessive Pronouns: Full Declensions",
    description:
      "See how possessive pronouns change in all 7 cases with gender and number.",
    sections: [
      {
        id: "moj",
        title: "Mój (First Person)",
        questions: "Kto? Co?",
        usage:
          "Indicates possession by the speaker / Wskazuje na posiadanie przez mówiącego",
        modalTitle: "Mój – First Person Singular / Plural",
        description: "Shows possession by the speaker.",
        genders: [
          {
            gender: "Masculine",
            subjectPronouns: "ja (singular), my (plural)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "mój", "moi"],
              ["Genitive", "mojego", "moich"],
              ["Dative", "mojemu", "moim"],
              ["Accusative", "mój / mojego", "moich"],
              ["Instrumental", "moim", "moimi"],
              ["Locative", "moim", "moich"],
              ["Vocative", "mój", "moi"],
            ],
          },
          {
            gender: "Feminine",
            subjectPronouns: "ja (singular), my (plural)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "moja", "moje"],
              ["Genitive", "mojej", "moich"],
              ["Dative", "mojej", "moim"],
              ["Accusative", "moją", "moje"],
              ["Instrumental", "moją", "moimi"],
              ["Locative", "mojej", "moich"],
              ["Vocative", "moja", "moje"],
            ],
          },
          {
            gender: "Neuter",
            subjectPronouns: "ja (singular), my (plural)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "moje", "moje"],
              ["Genitive", "mojego", "moich"],
              ["Dative", "mojemu", "moim"],
              ["Accusative", "moje", "moje"],
              ["Instrumental", "moim", "moimi"],
              ["Locative", "moim", "moich"],
              ["Vocative", "moje", "moje"],
            ],
          },
        ],
      },
      {
        id: "twoj",
        title: "Twój (Second Person)",
        questions: "Kto? Co?",
        usage:
          "Indicates possession by the person addressed / Wskazuje na posiadanie przez osobę, do której skierowane jest pismo",
        modalTitle: "Twój – Second Person Singular / Plural",
        description: "Shows possession by the person you are addressing.",
        genders: [
          {
            gender: "Masculine",
            subjectPronouns: "ty (singular), wy (plural)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "twój", "twoi"],
              ["Genitive", "twojego", "twoich"],
              ["Dative", "twojemu", "twoim"],
              ["Accusative", "twój / twojego", "twoich"],
              ["Instrumental", "twoim", "twoimi"],
              ["Locative", "twoim", "twoich"],
              ["Vocative", "twój", "twoi"],
            ],
          },
          {
            gender: "Feminine",
            subjectPronouns: "ty (singular), wy (plural)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "twoja", "twoje"],
              ["Genitive", "twojej", "twoich"],
              ["Dative", "twojej", "twoim"],
              ["Accusative", "twoją", "twoje"],
              ["Instrumental", "twoją", "twoimi"],
              ["Locative", "twojej", "twoich"],
              ["Vocative", "twoja", "twoje"],
            ],
          },
          {
            gender: "Neuter",
            subjectPronouns: "ty (singular), wy (plural)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "twoje", "twoje"],
              ["Genitive", "twojego", "twoich"],
              ["Dative", "twojemu", "twoim"],
              ["Accusative", "twoje", "twoje"],
              ["Instrumental", "twoim", "twoimi"],
              ["Locative", "twoim", "twoich"],
              ["Vocative", "twoje", "twoje"],
            ],
          },
        ],
      },
      {
        id: "jego-jej",
        title: "Jego/Jej (Third Person)",
        questions: "Kto? Co?",
        usage:
          "Indicates possession by he/she / Wskazuje posiadanie przez niego/nią",
        modalTitle: "Jego / Jej – Third Person Singular",
        description:
          "Shows possession by a third person (male, female, or object).",
        genders: [
          {
            gender: "Masculine",
            subjectPronouns: "on (he), ono (it)",
            columns: ["Case", "Singular"],
            rows: [
              ["Nominative", "jego"],
              ["Genitive", "jego"],
              ["Dative", "jemu"],
              ["Accusative", "jego"],
              ["Instrumental", "nim"],
              ["Locative", "nim"],
              ["Vocative", "jego"],
            ],
          },
          {
            gender: "Feminine",
            subjectPronouns: "ona (she)",
            columns: ["Case", "Singular"],
            rows: [
              ["Nominative", "jej"],
              ["Genitive", "jej"],
              ["Dative", "jej"],
              ["Accusative", "ją"],
              ["Instrumental", "nią"],
              ["Locative", "niej"],
              ["Vocative", "jej"],
            ],
          },
          {
            gender: "Neuter",
            subjectPronouns: "ono (it)",
            columns: ["Case", "Singular"],
            rows: [
              ["Nominative", "jego"],
              ["Genitive", "jego"],
              ["Dative", "jemu"],
              ["Accusative", "jego"],
              ["Instrumental", "nim"],
              ["Locative", "nim"],
              ["Vocative", "jego"],
            ],
          },
        ],
      },
      {
        id: "nasz",
        title: "Nasz (First Person Plural)",
        questions: "Kto? Co?",
        usage:
          "Indicates possession by we/us / Wskazuje posiadanie przez nas/nas",
        modalTitle: "Nasz – First Person Plural",
        description: "Shows possession by the speaker and others (we / us).",
        genders: [
          {
            gender: "Masculine",
            subjectPronouns: "my (we)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "nasz", "nasi"],
              ["Genitive", "naszego", "naszych"],
              ["Dative", "naszemu", "naszym"],
              ["Accusative", "nasz / naszego", "naszych"],
              ["Instrumental", "naszym", "naszymi"],
              ["Locative", "naszym", "naszych"],
              ["Vocative", "nasz", "nasi"],
            ],
          },
          {
            gender: "Feminine",
            subjectPronouns: "my (we)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "nasza", "nasze"],
              ["Genitive", "naszej", "naszych"],
              ["Dative", "naszej", "naszym"],
              ["Accusative", "naszą", "nasze"],
              ["Instrumental", "naszą", "naszymi"],
              ["Locative", "naszej", "naszych"],
              ["Vocative", "nasza", "nasze"],
            ],
          },
          {
            gender: "Neuter",
            subjectPronouns: "my (we)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "nasze", "nasze"],
              ["Genitive", "naszego", "naszych"],
              ["Dative", "naszemu", "naszym"],
              ["Accusative", "nasze", "nasze"],
              ["Instrumental", "naszym", "naszymi"],
              ["Locative", "naszym", "naszych"],
              ["Vocative", "nasze", "nasze"],
            ],
          },
        ],
      },
      {
        id: "wasz",
        title: "Wasz (Second Person Plural)",
        questions: "Kto? Co?",
        usage:
          "Indicates possession by you (plural) / Wskazuje na posiadanie przez Ciebie (liczba mnoga)",
        modalTitle: "Wasz – Second Person Plural",
        description:
          "Shows possession by the people you are addressing (you all / you plural).",
        genders: [
          {
            gender: "Masculine",
            subjectPronouns: "wy (you plural)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "wasz", "wasi"],
              ["Genitive", "waszego", "waszych"],
              ["Dative", "waszemu", "waszym"],
              ["Accusative", "wasz / waszego", "waszych"],
              ["Instrumental", "waszym", "waszymi"],
              ["Locative", "waszym", "waszych"],
              ["Vocative", "wasz", "wasi"],
            ],
          },
          {
            gender: "Feminine",
            subjectPronouns: "wy (you plural)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "wasza", "wasze"],
              ["Genitive", "waszej", "waszych"],
              ["Dative", "waszej", "waszym"],
              ["Accusative", "waszą", "wasze"],
              ["Instrumental", "waszą", "waszymi"],
              ["Locative", "waszej", "waszych"],
              ["Vocative", "wasza", "wasze"],
            ],
          },
          {
            gender: "Neuter",
            subjectPronouns: "wy (you plural)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "wasze", "wasze"],
              ["Genitive", "waszego", "waszych"],
              ["Dative", "waszemu", "waszym"],
              ["Accusative", "wasze", "wasze"],
              ["Instrumental", "waszym", "waszymi"],
              ["Locative", "waszym", "waszych"],
              ["Vocative", "wasze", "wasze"],
            ],
          },
        ],
      },
      {
        id: "ich",
        title: "Ich (Third Person Plural)",
        questions: "Kto? Co?",
        usage:
          "Indicates possession by they / Wskazuje na posiadanie przez nich",
        modalTitle: "Ich – Third Person Plural",
        description: "Shows possession by third person plural (they / them).",
        genders: [
          {
            gender: "Masculine",
            subjectPronouns: "oni (they, masculine personal)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "ich", "ich"],
              ["Genitive", "ich", "ich"],
              ["Dative", "im", "im"],
              ["Accusative", "ich", "ich"],
              ["Instrumental", "nimi", "nimi"],
              ["Locative", "nich", "nich"],
              ["Vocative", "ich", "ich"],
            ],
          },
          {
            gender: "Feminine",
            subjectPronouns: "one (they, feminine)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "ich", "ich"],
              ["Genitive", "ich", "ich"],
              ["Dative", "im", "im"],
              ["Accusative", "je", "je"],
              ["Instrumental", "nimi", "nimi"],
              ["Locative", "nich", "nich"],
              ["Vocative", "ich", "ich"],
            ],
          },
          {
            gender: "Neuter",
            subjectPronouns: "one (they, neuter)",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Nominative", "ich", "ich"],
              ["Genitive", "ich", "ich"],
              ["Dative", "im", "im"],
              ["Accusative", "je", "je"],
              ["Instrumental", "nimi", "nimi"],
              ["Locative", "nich", "nich"],
              ["Vocative", "ich", "ich"],
            ],
          },
        ],
      },
      {
        id: "swoj",
        title: "Swój (Reflexive)",
        questions: "Kto? Co?",
        usage: "Reflexive possession (own) / Posiadanie refleksyjne (własne)",
        modalTitle: "Swój – Reflexive Possessive",
        description:
          "Shows possession referring back to the subject of the sentence. Can be used with all persons (first, second, third) and both singular and plural.",
        genders: [
          {
            gender: "Masculine",
            subjectPronouns: "ja, ty, on, my, wy, oni",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Genitive", "swojego", "swoich"],
              ["Dative", "swojemu", "swoim"],
              ["Accusative", "swój / swojego", "swoich"],
              ["Instrumental", "swoim", "swoimi"],
              ["Locative", "swoim", "swoich"],
              ["Vocative", "swój", "swoi"],
            ],
          },
          {
            gender: "Feminine",
            subjectPronouns: "ja, ty, ona, my, wy, one",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Genitive", "swojej", "swoich"],
              ["Dative", "swojej", "swoim"],
              ["Accusative", "swoją", "swoje"],
              ["Instrumental", "swoją", "swoimi"],
              ["Locative", "swojej", "swoich"],
              ["Vocative", "swoja", "swoje"],
            ],
          },
          {
            gender: "Neuter",
            subjectPronouns: "ja, ty, ono, my, wy, one",
            columns: ["Case", "Singular", "Plural"],
            rows: [
              ["Genitive", "swojego", "swoich"],
              ["Dative", "swojemu", "swoim"],
              ["Accusative", "swoje", "swoje"],
              ["Instrumental", "swoim", "swoimi"],
              ["Locative", "swoim", "swoich"],
              ["Vocative", "swoje", "swoje"],
            ],
          },
        ],
      },
      {
        id: "reflexive-personal",
        title: "Się / Sobie / Siebie (Reflexive Personal)",
        questions: "Kogo? Komu? Co?",
        usage:
          "Reflexive actions (verbs acting on the subject themselves) / Czynności zwrotne (czasowniki odnoszące się do samego podmiotu)",
        modalTitle: "Się / Sobie / Siebie – Reflexive Personal Pronouns",
        description:
          "Used with verbs to indicate the action refers back to the subject.",
        specialTable: {
          columns: [
            "Case",
            "Singular (SIĘ)",
            "Plural (SIĘ)",
            "Singular (SIEBIE)",
            "Plural (SIEBIE)",
          ],
          rows: [
            ["Genitive", "się", "się", "siebie", "siebie"],
            ["Dative", "-", "-", "sobie", "sobie"],
            ["Accusative", "się", "się", "siebie", "siebie"],
            ["Instrumental", "-", "-", "sobą", "sobą"],
            ["Locative", "-", "-", "sobie", "sobie"],
          ],
        },
      },
      {
        id: "reflexive-intensifier",
        title: "Sam / Sama / Samo / Sami / Same (Reflexive Intensifier)",
        questions: "Kto? Co?",
        usage:
          'Emphasizes "by oneself, alone" / Podkreśla "samodzielnie, samemu"',
        modalTitle: "Sam / Sama / Samo / Sami / Same – Reflexive Intensifiers",
        description:
          "Used to emphasize that the subject performs the action alone or personally.",
        genders: [
          {
            gender: "Masculine",
            subjectPronouns: "ja, ty, on, my, wy, oni",
            columns: ["Singular", "Plural"],
            rows: [["sam", "sami"]],
          },
          {
            gender: "Feminine",
            subjectPronouns: "ja, ty, ona, my, wy, one",
            columns: ["Singular", "Plural"],
            rows: [["sama", "same"]],
          },
          {
            gender: "Neuter",
            subjectPronouns: "ja, ty, ono, my, wy, one",
            columns: ["Singular", "Plural"],
            rows: [["samo", "same"]],
          },
        ],
      },
    ],
  },
};

export default possessivePronounsData;
