const prepositionsData = {
  prepositions: {
    title: "Polish Prepositions",
    description:
      "This chart presents the most common Polish prepositions, explaining their meanings, usage, and the grammatical cases they govern. Examples show how each preposition changes depending on motion or position.",
    sections: [
      {
        id: "genitive",
        title: "Prepositions governing the GENITIVE (dopełniacz)",
        questions: "Kogo? Czego?",
        usage: "Origin, possession, absence, or movement away from something",
        modalTitle: "Genitive Case – Prepositions",
        description:
          "The following prepositions require the genitive case in Polish:",
        columns: ["Preposition", "Meaning", "Example", "Translation"],
        rows: [
          ["bez", "without", "bez cukru", "without sugar"],
          [
            "blisko / niedaleko / daleko od",
            "near / not far / far from",
            "blisko domu",
            "near the house",
          ],
          ["do", "to, into", "idę do szkoły", "I'm going to school"],
          ["od", "from, since", "od kolegi", "from a friend"],
          ["dla", "for", "prezent dla mamy", "a gift for mom"],
          [
            "z / ze",
            "from, out of",
            "wracam z pracy",
            "I'm coming back from work",
          ],
          ["spoza", "from outside", "spoza miasta", "from outside the city"],
          [
            "u",
            "at (someone's place)",
            "jestem u lekarza",
            "I'm at the doctor's",
          ],
          ["koło / obok", "near, beside", "koło sklepu", "near the shop"],
          ["podczas", "during", "podczas lekcji", "during the lesson"],
          [
            "wobec",
            "towards, in relation to",
            "wobec problemu",
            "in relation to the problem",
          ],
          [
            "wokół / dookoła / naokoło",
            "around",
            "wokół stołu",
            "around the table",
          ],
          ["zamiast", "instead of", "zamiast kawy", "instead of coffee"],
          ["poza", "beyond, outside", "poza domem", "outside the house"],
          ["pomimo / mimo", "despite", "mimo deszczu", "despite the rain"],
        ],
      },
      {
        id: "accusative",
        title: "Prepositions governing the ACCUSATIVE (biernik)",
        questions: "Kogo? Co?",
        usage:
          "These usually indicate movement toward, time duration, or object of action",
        modalTitle: "Accusative Case – Prepositions",
        description:
          "The following prepositions require the accusative case in Polish:",
        columns: ["Preposition", "Meaning", "Example", "Translation"],
        rows: [
          [
            "na",
            "onto, for (purpose)",
            "jadę na uniwersytet",
            "I'm going to the university",
          ],
          [
            "w / we",
            "into, at (movement)",
            "wchodzę w las",
            "I'm going into the forest",
          ],
          ["przez", "through, across", "przez park", "through the park"],
          [
            "o",
            "about (time, topic)",
            "o 5 rano / rozmawiam o tobie",
            "at 5 a.m. / I talk about you",
          ],
          ["po", "for (purpose, after)", "idę po chleb", "I'm going for bread"],
          [
            "za",
            "for (in exchange for)",
            "zapłaciłem za bilet",
            "I paid for the ticket",
          ],
          ["na (czas)", "for (time period)", "na godzinę", "for an hour"],
          [
            "przeciw / przeciwko",
            "against",
            "przeciw wojnie",
            "against the war",
          ],
          [
            "między / pomiędzy (with motion)",
            "between (motion)",
            "wchodzę między drzewa",
            "I go between trees",
          ],
        ],
      },
      {
        id: "locative",
        title: "Prepositions governing the LOCATIVE (miejscownik)",
        questions: "O kim? O czym?",
        usage:
          "These are used mostly for static location or topic (used only with na, w, o, po, przy)",
        modalTitle: "Locative Case – Prepositions",
        description:
          "The following prepositions require the locative case in Polish:",
        columns: ["Preposition", "Meaning", "Example", "Translation"],
        rows: [
          ["na", "on, at", "na stole", "on the table"],
          ["w / we", "in, inside", "w domu", "in the house"],
          ["o", "about, concerning", "myślę o tobie", "I'm thinking about you"],
          ["po", "after, along", "po lekcji", "after the lesson"],
          ["przy", "by, near", "przy oknie", "by the window"],
        ],
      },
      {
        id: "instrumental",
        title: "Prepositions governing the INSTRUMENTAL (narzędnik)",
        questions: "Z kim? Z czym?",
        usage:
          "Used to express means, accompaniment, or location after certain prepositions.",
        modalTitle: "Instrumental Case – Prepositions",
        description:
          "The following prepositions require the instrumental case in Polish:",
        columns: ["Preposition", "Meaning", "Example", "Translation"],
        rows: [
          ["z / ze", "with", "z przyjacielem", "with a friend"],
          ["nad", "above, over", "nad stołem", "above the table"],
          ["pod", "under, below", "pod łóżkiem", "under the bed"],
          [
            "przed",
            "before, in front of",
            "przed domem",
            "in front of the house",
          ],
          ["za", "behind, beyond", "za domem", "behind the house"],
          [
            "między / pomiędzy",
            "between, among",
            "między ludźmi",
            "among people",
          ],
        ],
      },
      {
        id: "dative",
        title: "Prepositions governing the DATIVE (celownik)",
        questions: "Komu? Czemu?",
        usage: "Used for expressing benefit, direction toward (figuratively)",
        modalTitle: "Dative Case – Prepositions",
        description:
          "The following prepositions require the dative case in Polish:",
        columns: ["Preposition", "Meaning", "Example", "Translation"],
        rows: [
          ["dzięki", "thanks to", "dzięki tobie", "thanks to you"],
          ["ku", "toward", "ku słońcu", "toward the sun"],
          [
            "wbrew",
            "against (the will, contrary to)",
            "wbrew zasadom",
            "against the rules",
          ],
          ["przeciw / przeciwko", "against", "przeciwko niemu", "against him"],
        ],
      },
      {
        id: "multiple-cases",
        title:
          "Prepositions governing MULTIPLE CASES (depending on motion or position)",
        questions: "-",
        usage:
          "These change meaning depending on whether there's motion (Accusative) or location (Locative / Instrumental).",
        modalTitle: "Prepositions with Multiple Cases",
        description:
          "Some Polish prepositions can require different cases depending on motion or position:",
        columns: ["Preposition", "Motion?", "Case", "Example", "Translation"],
        rows: [
          [
            "na",
            "motion",
            "Accusative",
            "jadę na uczelnię",
            "I'm going to the university",
          ],
          [
            "na",
            "position",
            "Locative",
            "jestem na uczelni",
            "I'm at the university",
          ],
          [
            "w / we",
            "motion",
            "Accusative",
            "wchodzę w dom",
            "I'm entering the house",
          ],
          [
            "w / we",
            "position",
            "Locative",
            "jestem w domu",
            "I'm in the house",
          ],
          [
            "pod",
            "motion",
            "Accusative",
            "kładę coś pod łóżko",
            "I put something under the bed",
          ],
          [
            "pod",
            "position",
            "Instrumental",
            "jest pod łóżkiem",
            "it's under the bed",
          ],
          [
            "nad",
            "motion",
            "Accusative",
            "lecę nad morze",
            "I'm flying over the sea",
          ],
          [
            "nad",
            "position",
            "Instrumental",
            "mieszkam nad morzem",
            "I live by the sea",
          ],
          [
            "przed",
            "motion",
            "Accusative",
            "wyszedł przed dom",
            "he went out in front of the house",
          ],
          [
            "przed",
            "position",
            "Instrumental",
            "stoi przed domem",
            "he's standing in front of the house",
          ],
          [
            "za",
            "motion",
            "Accusative",
            "idę za dom",
            "I'm going behind the house",
          ],
          [
            "za",
            "position",
            "Instrumental",
            "jestem za domem",
            "I'm behind the house",
          ],
          [
            "między",
            "motion",
            "Accusative",
            "wszedł między ludzi",
            "he went among people",
          ],
          [
            "między",
            "position",
            "Instrumental",
            "siedzi między ludźmi",
            "he sits among people",
          ],
        ],
      },
      {
        id: "summary",
        title: "Summary by Function",
        questions: "Prepositions Summary",
        usage: "-",
        modalTitle: "Summary of Polish Prepositions",
        description:
          "This table provides a quick reference of common prepositions by their function:",
        columns: ["Function", "Common Prepositions"],
        rows: [
          ["Location", "w, na, przy, pod, nad, za, między"],
          ["Direction (movement)", "do, na, w, pod, nad, za, między"],
          ["Source / Origin", "z, od, spoza"],
          ["Time", "przed, po, podczas, o, na"],
          ["Cause / Purpose", "dla, dzięki, przez"],
          ["Accompaniment / Means", "z"],
          ["Opposition", "przeciw, mimo, wbrew"],
          ["Possession / Relation", "u, wobec, względem"],
        ],
      },
    ],
  },
};

export default prepositionsData;
