const verbsData = {
  mostCommon: {
    title: "Most Common Used Verbs",
    description: "Popular Polish verbs organized by conjugation class",
    sections: [
      {
        id: "first-class",
        title: "First Class (-ę, -esz)",
        description: "Infinitive, I, You, English meaning",
        modalTitle: "First Class Verbs (-ę, -esz)",
        columns: ["Infinitive", "I", "You", "English"],
        rows: [
          ["brać", "biorę", "bierzesz", "to take"],
          ["iść", "idę", "idziesz", "to go"],
          ["dostawać", "dostaję", "dostajesz", "to get"],
          ["pracować", "pracuję", "pracujesz", "to work"],
          ["dawać", "daję", "dajesz", "to give"],
          ["próbować", "próbuję", "próbujesz", "to try"],
          ["potrzebować", "potrzebuję", "potrzebujesz", "to need"],
          ["czuć", "czuję", "czujesz", "to feel"],
          ["kłaść", "kładę", "kładziesz", "to put"],
          ["chcieć", "chcę", "chcesz", "to want"],
          ["żyć", "żyję", "żyjesz", "to live"],
          ["pisać", "piszę", "piszesz", "to write"],
          ["dodawać", "dodaję", "dodajesz", "to add"],
          ["rosnąć", "rosnę", "rośniesz", "to grow"],
          ["kupować", "kupuję", "kupujesz", "to buy"],
          ["budować", "buduję", "budujesz", "to build"],
          ["zostawać", "zostaję", "zostajesz", "to stay"],
          ["sprzedawać", "sprzedaję", "sprzedajesz", "to sell"],
          ["decydować", "decyduję", "decydujesz", "to decide"],
          ["jechać", "jadę", "jedziesz", "to drive"],
          ["dziękować", "dziękuję", "dziękujesz", "to thank"],
        ],
      },
      {
        id: "second-class",
        title: "Second Class (-ię / -ę, -isz / -ysz)",
        description: "Infinitive, I, You, English meaning",
        modalTitle: "Second Class Verbs (-ię / -ę, -isz / -ysz)",
        columns: ["Infinitive", "I", "You", "English"],
        rows: [
          ["robić", "robię", "robisz", "to do / to make"],
          ["mówić", "mówię", "mówisz", "to speak"],
          ["myśleć", "myślę", "myślisz", "to think"],
          ["widzieć", "widzę", "widzisz", "to see"],
          ["przychodzić", "przychodzę", "przychodzisz", "to come / to arrive"],
          ["dzwonić", "dzwonię", "dzwonisz", "to call"],
          ["słyszeć", "słyszę", "słyszysz", "to hear"],
          ["lubić", "lubię", "lubisz", "to like"],
          ["wierzyć", "wierzę", "wierzysz", "to believe"],
          ["przynosić", "przynoszę", "przynosisz", "to bring"],
          ["siedzieć", "siedzę", "siedzisz", "to sit"],
          ["stać", "stoję", "stoisz", "to stand"],
          ["płacić", "płacę", "płacisz", "to pay"],
          ["uczyć", "uczę", "uczysz", "to teach"],
          ["uczyć się", "uczę się", "uczysz się", "to learn"],
          ["tworzyć", "tworzę", "tworzysz", "to create"],
          ["chodzić", "chodzę", "chodzisz", "to walk"],
          ["nienawidzić", "nienawidzę", "nienawidzisz", "to hate"],
          ["spać", "śpię", "śpisz", "to sleep"],
        ],
      },
      {
        id: "third-class",
        title: "Third Class (-am, -asz)",
        description: "Infinitive, I, You, English meaning",
        modalTitle: "Third Class Verbs (-am, -asz)",
        columns: ["Infinitive", "I", "You", "English"],
        rows: [
          ["mieć", "mam", "masz", "to have"],
          ["przyjeżdżać", "przyjeżdżam", "przyjeżdżasz", "to come / to arrive"],
          ["używać", "używam", "używasz", "to use"],
          ["szukać", "szukam", "szukasz", "to search"],
          ["pytać", "pytam", "pytasz", "to ask"],
          ["trzymać", "trzymam", "trzymasz", "to hold"],
          ["pomagać", "pomagam", "pomagasz", "to help"],
          ["zaczynać", "zaczynam", "zaczynasz", "to begin"],
          ["grać", "gram", "grasz", "to play"],
          ["spotykać", "spotykam", "spotykasz", "to meet"],
          ["zmieniać", "zmieniam", "zmieniasz", "to change"],
          ["oglądać", "oglądam", "oglądasz", "to watch"],
          ["otwierać", "otwieram", "otwierasz", "to open"],
          ["pamiętać", "pamiętam", "pamiętasz", "to remember"],
          ["kochać", "kocham", "kochasz", "to love"],
          ["czekać", "czekam", "czekasz", "to wait"],
          ["umierać", "umieram", "umierasz", "to die"],
          ["spadać", "spadam", "spadasz", "to fall"],
          ["zabijać", "zabijam", "zabijasz", "to kill"],
          ["śpiewać", "śpiewam", "śpiewasz", "to sing"],
          ["pływać", "pływam", "pływasz", "to swim"],
          ["wybierać", "wybieram", "wybierasz", "to choose"],
        ],
      },
      {
        id: "fourth-class",
        title: "Fourth Class (-em, -esz)",
        description: "Infinitive, I, You, English meaning",
        modalTitle: "Fourth Class Verbs (-em, -esz)",
        columns: ["Infinitive", "I", "You", "English"],
        rows: [
          ["rozumieć", "rozumiem", "rozumiesz", "to understand"],
          ["wiedzieć", "wiem", "wiesz", "to know"],
          ["umieć", "umiem", "umiesz", "can / be able"],
          ["jeść", "jem", "jesz", "to eat"],
        ],
      },
    ],
  },
  perfectiveImperfective: {
    title: "Perfective & Imperfective Verbs",
    description:
      "Shows the infinitive form of verbs: imperfective (ongoing/habitual actions) vs. perfective (completed actions)",
    sections: [
      {
        id: "imperfective-class",
        title: "Imperfective Verbs",
        description:
          "Actions in progress, repeated, habitual, or ongoing – show the verb in its base form (Infinitive) with the English meaning.",
        modalTitle: "Imperfective Verbs",
        columns: ["Infinitive", "English"],
        rows: [
          ["robić", "to do / to make"],
          ["mówić", "to speak"],
          ["pisać", "to write"],
          ["czytać", "to read"],
          ["jeść", "to eat"],
          ["pić", "to drink"],
          ["iść", "to go (on foot)"],
          ["jechać", "to go (by vehicle)"],
          ["dawać", "to give"],
          ["brać", "to take"],
          ["kupować", "to buy"],
          ["sprzedawać", "to sell"],
          ["pracować", "to work"],
          ["uczyć się", "to learn"],
          ["myśleć", "to think"],
          ["widzieć", "to see"],
          ["słyszeć", "to hear"],
          ["mieć", "to have"],
          ["być", "to be"],
          ["chcieć", "to want"],
        ],
      },
      {
        id: "perfective-class",
        title: "Perfective Verbs",
        description:
          "Completed or one-time actions – show the verb in its completed form (Infinitive) with the English meaning.",
        modalTitle: "Perfective Verbs",
        columns: ["Infinitive", "English"],
        rows: [
          ["zrobić", "to do / to make (completed)"],
          ["powiedzieć", "to say (completed)"],
          ["napisać", "to write (completed)"],
          ["przeczytać", "to read (completed)"],
          ["zjeść", "to eat (completed)"],
          ["wypić", "to drink (completed)"],
          ["pójść", "to go (completed, on foot)"],
          ["pojechać", "to go (completed, by vehicle)"],
          ["dać", "to give (completed)"],
          ["wziąć", "to take (completed)"],
          ["kupić", "to buy (completed)"],
          ["sprzedać", "to sell (completed)"],
          ["popracować", "to work (for a while)"],
          ["nauczyć się", "to learn (completed)"],
          ["pomyśleć", "to think (completed)"],
          ["zobaczyć", "to see (completed)"],
          ["usłyszeć", "to hear (completed)"],
          ["dostać", "to get (completed)"],
          ["zostać", "to become (completed)"],
          ["zechcieć", "to want (at a moment)"],
        ],
      },
    ],
  },
};

export default verbsData;
